package com.calendarjsf.modelos;
// Generated 05-mar-2019 8:58:10 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="calendar"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="usuario")} 
)
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private String usuario;
     private String pass;
     private Date fechaCreacion;
     private String email;

    public Usuarios() {
        this.usuario = "";
        this.pass = "";
        this.fechaCreacion = null;
        this.email = "";
    }

    public Usuarios(String usuario, String pass, Date fechaCreacion, String email) {
       this.usuario = usuario;
       this.pass = pass;
       this.fechaCreacion = fechaCreacion;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="usuario", unique=true, nullable=false, length=55)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="Pass", nullable=false)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaCreacion", nullable=false, length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


